name: Flake8

on:
   # Trigger the workflow on push or pull request,
   # but only for the main branch
   push:
     branches:
       - main
       - master
   pull_request:
     branches:
       - main
       - master

jobs:
  pytest:
    name: ${{ matrix.name }}
    runs-on: "${{ matrix.os }}"

    env:
      PYTHON_VERSION: "${{ matrix.python-version }}"
      TESTS: "tests/"

    strategy:
      # Prevent all build to stop if a single one fails
      fail-fast: false

      matrix:
        name: [
           python36-ubuntu1804,
           python38-ubuntu2004,
           python37-macOS
        ]
        include:
        - name: python36-ubuntu1804
          python-version: 3.6
          os: ubuntu-18.04

        - name: python38-ubuntu2004
          python-version: 3.8
          os: ubuntu-20.04

    #    - name: python37-macOs
    #      python-version: 3.7
    #      os: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    #- name: Mac Install
    #  if: matrix.os == 'macos-latest'
    #  run: |
    #    sudo apt-get install python3-setuptools -y
    #    pip3 install --upgrade pip
    #    pip3 install -e .
    #    pip3 install -r requirements.txt
    - name: Linux Install
      if: matrix.os != 'macos-latest'
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Lint with flake8
      run: |
        flake8 --builtins=ArgumentError .
